export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_REQUEST = "GET_REQUEST";
export const REQUEST_LOADING = "REQUEST_LOADING";
export const REQUEST_NOT_FOUND = "REQUEST_NOT_FOUND";
export const CLEAR_CURRENT_REQUEST = "CLEAR_CURRENT_REQUEST";
export const GET_REQUESTS = "GET_REQUESTS";
